import {
    faArrowTrendUp,
    faBuildingColumns,
    faCar,
    faChampagneGlasses,
    faDesktop,
    faFileInvoiceDollar,
    faGasPump,
    faHouse,
    faPeopleRoof,
    faPiggyBank,
    faPrescriptionBottleMedical,
    faShirt,
    faSmoking,
    faTableTennisPaddleBall,
    faTruckPlane,
    faUmbrellaBeach,
    faUtensils
} from '@fortawesome/free-solid-svg-icons';

export const expenseCategoryIcons = [
    {name: 'Food', icon: faUtensils},
    {name: 'Home', icon: faHouse},
    {name: 'Gas', icon: faGasPump},
    {name: 'Transport', icon: faTruckPlane},
    {name: 'Car', icon: faCar},
    {name: 'Health', icon: faPrescriptionBottleMedical},
    {name: 'Drugs', icon: faSmoking},
    {name: 'Clothes', icon: faShirt},
    {name: 'Electronics', icon: faDesktop},
    {name: 'Hobby', icon: faTableTennisPaddleBall},
    {name: 'Vacation', icon: faUmbrellaBeach},
    {name: 'Family', icon: faPeopleRoof},
    {name: 'Bills', icon: faFileInvoiceDollar},
    {name: 'Bank loan', icon: faBuildingColumns},
    {name: 'Investments', icon: faArrowTrendUp},
    {name: 'Party', icon: faChampagneGlasses},
    {name: 'Savings', icon: faPiggyBank},
]